package com.eagle.app.security

/**
 * Privacy-minimized, versioned security telemetry record.
 *
 * This contract deliberately contains no secrets, plaintext, private keys, or model outputs.
 * IDs must be opaque/pseudonymous values generated by the owning layer.
 */
data class SecurityEvent(
    val schemaVersion: Int,
    val type: Type,
    val monotonicTimestampMillis: Long,
    val contextId: String,
    val peerPseudonym: String?,
    val protocolState: SessionStateMachine.State?,
    val outcome: Outcome,
    val boundedCount: Long = 1L
) {
    enum class Type {
        RATE_LIMIT_ALLOWED,
        RATE_LIMIT_LIMITED,
        REPLAY_ACCEPTED,
        REPLAY_DUPLICATE,
        REPLAY_TOO_OLD,
        REPLAY_INVALID_SEQUENCE,
        SESSION_TRANSITION_ACCEPTED,
        SESSION_TRANSITION_REJECTED
    }

    enum class Outcome {
        ACCEPTED,
        REJECTED,
        LIMITED,
        INVALID
    }

    init {
        require(schemaVersion > 0) { "schemaVersion must be positive" }
        require(monotonicTimestampMillis >= 0) {
            "timestamp must be monotonic milliseconds >= 0"
        }
        require(contextId.isNotBlank()) { "contextId must not be blank" }
        require(contextId.length <= MAX_ID_LENGTH) { "contextId is too long" }
        require(peerPseudonym == null || peerPseudonym.length <= MAX_ID_LENGTH) {
            "peer pseudonym is too long"
        }
        require(boundedCount in 0..MAX_BOUNDED_COUNT) {
            "boundedCount is outside the allowed range"
        }
    }

    companion object {
        const val MAX_ID_LENGTH = 128
        const val MAX_BOUNDED_COUNT = 1_000_000L
    }
}
